name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build_synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cdk/package-lock.json

      - name: Install
        working-directory: cdk
        run: npm ci

      - name: Build
        working-directory: cdk
        run: npm run build

      - name: CDK synth (sanity check)
        working-directory: cdk
        run: npm run synth

  # Optional: real integration check using LocalStack
  localstack_integration:
    # Keep PRs fast: only run this after merge to main
    if: github.ref == 'refs/heads/main'
    needs: build_synth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cdk/package-lock.json

      - name: Start LocalStack
        uses: localstack/setup-localstack@v0
        with:
          image-tag: latest

      - name: Set AWS env (dummy creds for LocalStack)
        run: |
          echo "AWS_ACCESS_KEY_ID=test" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Install
        working-directory: cdk
        run: npm ci

      - name: Deploy to LocalStack
        working-directory: cdk
        env:
          LOCALSTACK_HOSTNAME: localhost
          EDGE_PORT: 4566
        run: npm run local:deploy
